cart/urls.py
from django.urls import path
from .import views
app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('searchapp/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                    document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.urls import path
from .import views
app_name='searchapp'

urlpatterns = [
   
    path('',views.SearchResult,name='SearchResult'),
]

shop/urls.py
from django.urls import path
from .import views
app_name='shop'

urlpatterns = [
   
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='productCatdetail')
]

cart/models.py
from django.db import models
from shop.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return'{}'.format( self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return'{}'.format(self.product)

searchapp/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])
    def __str__(self):
        return'{}'.format(self.name)
    
class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category(), on_delete=models.CASCADE)
    image=models.ImageField(upload_to='category',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def get_url(self):
        return reverse('shop:productCatdetail',args=[self.category.slug,self.slug])
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    
    def __str__(self):
        return'{}'.format(self.name)

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

searchapp/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query)|Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Category,Product
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def index(request):
    return HttpResponse('Hey')

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
        paginator=Paginator(products_list,6)
        try:
            page=int(request.GET.get('page','1'))
        except:
            page=1
        try:
            products=paginator.page(page)
        except (EmptyPage,InvalidPage):
            products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products_list})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html',{'product':product})

templates/base.html
{% load static %}
<html>
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js">
    
    
    <!--<link rel="  stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
    </div>
    {% include 'footer.html' %}
    <!--<script src="{% static 'js/popper.min.js' %}"></script>-->
    <!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
    
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

This is cart page proceed to review order
{% endblock %}
{% block title %}
Cart - ABC private limited
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart is Empty</h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'shop:allProdCart' %}">Here</a>to continue Shopping
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart</h1>
        <br>

    </div>
    <div class="row mx-auto">
      <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">Your Items</th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width: 100px; height: 100px;" class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU:{{cart_item.product.id}}
                        <br>
                        Price:${{cart_item.product.price}}
                        <br>
                        Qty:{{cart_item.quantity}} x $ {{cart_item}} 

                    </td>
                    <td>
                        ${{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %} " class="custom_a"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
                          </svg></a>&nbsp;
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle-fill" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7z"/>
                          </svg></a>&nbsp;
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                          </svg></a>
                    </td>
                    {% else %}
                    <td>
                        
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle-fill" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7z"/>
                          </svg></a>&nbsp;
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                          </svg></a>&nbsp;
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}

            </tbody>

        </table>
      </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>CHECKOUT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Please review your shopping cart item before proceeding with the order payment</td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your Total is: <strong> {{ total }} </strong>
                    </td>
                </tr>

            </tbody>

        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allProdCat' %} " class="btn btn-secondary btn-block my_custom_button">Continue</a>

        </div>

    </div>
</div>
    
</div>
{% endif %}
</div>
</div>
</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
     {{ category.description|truncatewords:155 }}
  {% else %}
     Welcome to ABC stores where you can buy different items....
  {% endif %}
{% endblock %}
{% block title %}
  {% if category %}
      {{ category.name }} - ABC stores
  {% else %}
     See our new collections in ABC stores 
  {% endif %}
{% endblock %}
{% block content %}
   {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                <p><a href="{% url 'shop:allProdCat' %}">Our Product Collections</a></p>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
        <img class="my_image my_image_padding" src="{% static 'img/dairy-farming-banner.png' %}" alt="Our Products">
        <br>
        <div>
            <h1 class="text-center my_title">Our Product Collections</h1>
            <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec nulla luctus, cursus purus et, laoreet felis. Sed vel elementum erat. Donec ex ipsum, tempus ac ante eu, mollis imperdiet elit. Donec porta feugiat risus a condimentum. Proin convallis purus ante, sit amet rhoncus sem commodo vel. Etiam auctor malesuada libero id imperdiet. In ac lectus eget nunc lobortis ultrices. Vivamus vel sapien lacinia, commodo nulla nec, sodales leo. Donec tellus orci, faucibus nec magna hendrerit, suscipit sagittis eros. Sed semper erat turpis, ac accumsan arcu iaculis eu. Integer quam leo, fermentum a molestie in, elementum a sapien. Donec sit amet hendrerit odio, ultrices condimentum augue.</p>
        </div>
        {% endif %}
        <div class="container">
            <div class="row mx_auto">
                {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                    <div class="card text-center" style="min-width:18rem;"> 
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                   </div>
                   <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                   </div>
                </div>
           
                {% endfor %}
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}
                 <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                       <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <br>
        </div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@copyrightABCprivatelimited. All rights Reserved</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>

        <a href="{% url 'shop:allProdCat' %}">       <img src="{% static 'img/logo.png' %}" alt="logimage">
    </center>
</header>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Shop
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
            {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
            
        </li>
        {% if item_count > 0  %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
          </svg>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg></button>
      </form>
    </div>
  </nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  
     {{ product.description|truncatewords:155 }}
 
 
{% endblock %}
{% block title %}
  {% if category %}
      {{ product.name }} - ABC stores
  
  {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}} ">{{product.category}}</a>|{{product.name}}</p>
    </div>
    <div class="container">
    <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width: 18rem;">
                    <img src="{{product.image.url}}" alt="{{product.name}}" >
                </div>
            </div>
        <div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div>
                    <h1 class="my_prod_title">{{product.name}}</h1>
                    <p>${{product.price}}</p>
                    <p class="my_title">Product Description</p>
                    <p class="text-justify my_prod_text">{{product.description}}</p>
                    {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                    {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}
   
    
    

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

we have variety of products
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">
      You have searched for : <b>"{{query}}"</b>
    </p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="min-width:18rem;"> 
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
           </div>
           <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
           </div>
        </div>
    </div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">0 result found</p>

    </div>
    {% endfor %}
</div>

{% endblock %}